# -*- coding: utf-8 -*-
"""speech_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EoGQanbS2c0MVnfaf-GqVq1w_Bs0xkK
"""

from tkinter import *
import speech_recognition

top = Tk()

top.geometry("500x500")


def printSomething(x):
    # if you want the button to disappear:
     # button.destroy() or button.pack_forget()
    label = Label(top, text= x)
    #this creates a new label to the GUI
    label.pack()


def clicked():
    r = speech_recognition.Recognizer()
    with speech_recognition.Microphone() as source:
        r.adjust_for_ambient_noise(source,duration=5)
        print('speak now')
        audio = r.listen(source)
        text = r.recognize_google(audio)
        printSomething("Did you say :\n")
        printSomething(text)



b = Button(top,text ="Speaknow",command=clicked)

b.pack()

top.mainloop()